
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__hotkeys_adaptor_h__adaptor__H__
#define __sdbuscpp__hotkeys_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace soundux {

class hotkeys_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.soundux.hotkeys";

protected:
    hotkeys_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    hotkeys_adaptor(const hotkeys_adaptor&) = delete;
    hotkeys_adaptor& operator=(const hotkeys_adaptor&) = delete;
    hotkeys_adaptor(hotkeys_adaptor&&) = delete;
    hotkeys_adaptor& operator=(hotkeys_adaptor&&) = delete;

    ~hotkeys_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("emit").withInputParamNames("keys").implementedAs([this](const std::vector<int32_t>& keys){ return this->emit(keys); })
                          , sdbus::registerMethod("emit_name").withInputParamNames("keys").implementedAs([this](const std::vector<std::string>& keys){ return this->emit_name(keys); })
                          ).forInterface(INTERFACE_NAME);
    }

private:
    virtual void emit(const std::vector<int32_t>& keys) = 0;
    virtual void emit_name(const std::vector<std::string>& keys) = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
